// flow-typed signature: c57cc5de6dd1127da62212d8120a2e21
// flow-typed version: <<STUB>>/reactackle_v^1.1.3/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reactackle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reactackle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reactackle/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reactackle/dist/index.js' {
  declare module.exports: $Exports<'reactackle/dist/index'>;
}
